### ISSUE TITLE
package ThriveGmbH.BottomNavigationBar.XF 1.0.2 is not compatible with netstandard1.4

### ISSUE THREAD

**Issue by angelru** [dewango/BottomNavigationBarXF#70]
any solution?

**Comment by n0tc0ding** [comment]
I had to add the classes manually to the android project and forms project. The only thing that doesn`t work is the tab color change.

**Comment by angelru** [comment]
@n0tc0ding  But it's compatible with netstandard?

**Comment by n0tc0ding** [comment]
@angelru , Is it the same problem with the  xamarin version? I could not install the nugget in my xamarin forms project so I had to add all the classes manually. It worked fine except the tab colors.

**Comment by angelru** [comment]
@n0tc0ding  but can you used PCL or NET Standard Class Library? thanks a lot!

**Comment by n0tc0ding** [comment]
@angelru yes it works on PCL
